### ISSUE TITLE
Supported Storage Drivers?

### ISSUE THREAD

**Issue by batmat** [5pi/docker-backup#21]
Hi,
I think the README would benefit greatly from having more details about the supported storage drivers. IIUC, only vfs/devicemapper is supported? For example, are overlay, btrfs, etc. supported?

Just tried locally (running on overlay) through the docker image, and it does not seem to work. And indeed, overlay leaves the vfs/dir empty. So I suppose this is the reason.

I'd have provided the PR myself if I was sure what to write in :-).

Thanks a lot.

**Comment by discordianfish** [comment]
Since this tool does *not* persist the container state itself but only the data volume and configuration to recreate the container, it doesn't care about the storage driver. So all storage drivers are supported.

**Comment by batmat** [comment]
OK, cool. Thanks
